import pygame

TextureBank = {}


TextureBank['INITIAL_SCREEN'] = pygame.image.load("images/background/initialscreen.png")
TextureBank['BACKGROUND'] = pygame.image.load("images/background/background.png")

TextureBank['START_GAME'] = pygame.image.load("images/menu/startgame.png")
TextureBank['GAMEOVER'] = pygame.image.load("images/menu/gameover.png")

TextureBank['INSTRUCAO_1'] = pygame.image.load("images/instrucao/instrucao1.png")
TextureBank['INSTRUCAO_2'] = pygame.image.load("images/instrucao/instrucao2.png")
TextureBank['INSTRUCAO_3'] = pygame.image.load("images/instrucao/instrucao3.png")

TextureBank['0'] = pygame.image.load("images/numeros/0.png")
TextureBank['1'] = pygame.image.load("images/numeros/1.png")
TextureBank['2'] = pygame.image.load("images/numeros/2.png")
TextureBank['3'] = pygame.image.load("images/numeros/3.png")
TextureBank['4'] = pygame.image.load("images/numeros/4.png")
TextureBank['5'] = pygame.image.load("images/numeros/5.png")
TextureBank['6'] = pygame.image.load("images/numeros/6.png")
TextureBank['7'] = pygame.image.load("images/numeros/7.png")
TextureBank['8'] = pygame.image.load("images/numeros/8.png")
TextureBank['9'] = pygame.image.load("images/numeros/9.png")

TextureBank['A'] = pygame.image.load("images/letras/A.png")
TextureBank['B'] = pygame.image.load("images/letras/B.png")
TextureBank['C'] = pygame.image.load("images/letras/C.png")
TextureBank['D'] = pygame.image.load("images/letras/D.png")
TextureBank['E'] = pygame.image.load("images/letras/E.png")
TextureBank['F'] = pygame.image.load("images/letras/F.png")
TextureBank['G'] = pygame.image.load("images/letras/G.png")
TextureBank['H'] = pygame.image.load("images/letras/H.png")
TextureBank['I'] = pygame.image.load("images/letras/I.png")
TextureBank['J'] = pygame.image.load("images/letras/J.png")
TextureBank['K'] = pygame.image.load("images/letras/K.png")
TextureBank['L'] = pygame.image.load("images/letras/L.png")
TextureBank['M'] = pygame.image.load("images/letras/M.png")
TextureBank['N'] = pygame.image.load("images/letras/N.png")
TextureBank['O'] = pygame.image.load("images/letras/O.png")
TextureBank['P'] = pygame.image.load("images/letras/P.png")
TextureBank['Q'] = pygame.image.load("images/letras/Q.png")
TextureBank['R'] = pygame.image.load("images/letras/R.png")
TextureBank['S'] = pygame.image.load("images/letras/S.png")
TextureBank['T'] = pygame.image.load("images/letras/T.png")
TextureBank['U'] = pygame.image.load("images/letras/U.png")
TextureBank['V'] = pygame.image.load("images/letras/V.png")
TextureBank['W'] = pygame.image.load("images/letras/W.png")
TextureBank['Y'] = pygame.image.load("images/letras/Y.png")
TextureBank['Z'] = pygame.image.load("images/letras/Z.png")

TextureBank['REWIND'] = pygame.image.load("images/icons/rewind.png")
TextureBank['FORWARD'] = pygame.image.load("images/icons/forward.png")
TextureBank['USERLIFE'] = pygame.image.load("images/icons/user_life.png")
TextureBank['PLAY'] = pygame.image.load("images/icons/play.png")
TextureBank['PAUSE'] = pygame.image.load("images/icons/pause.png")
TextureBank['PLAYAGAIN'] = pygame.image.load("images/icons/play_again.png")
TextureBank['SOUNDON'] = pygame.image.load("images/icons/sound.png")
TextureBank['SOUNDOFF'] = pygame.image.load("images/icons/sound_off.png")

TextureBank['PLAYER'] = pygame.image.load("images/balls/player.png")
TextureBank['POINTER'] = pygame.image.load("images/balls/pointer.png")
TextureBank['MURDERER'] = pygame.image.load("images/balls/murderer.png")
TextureBank['SAVER'] = pygame.image.load("images/balls/saver.png")